#! /bin/bash
set -e

DATE=`date +%Y-%m-%d`
TOPIC=""

ARGSTMP=`getopt -o t: --long topic: -n 'lb' -- "$@"`
eval set -- "$ARGSTMP"

while true; do
    case "$1" in
        -t|--topic)
            case "$2" in
                "") shift 2 ;;
                *) TOPIC=$2 ; shift 2 ;;
            esac ;;
        --) shift ; break ;;
    esac
done

if [ -z ${EDITOR+x} ]; then
    EDITOR="vim"
fi

if [ -z ${LBDIR+x} ]; then
    LBDIR="$HOME/notes/"
fi

if [ ! -e $LBDIR ]; then
    mkdir -p $LBDIR
fi

if [ "$TOPIC" == "" ]; then
    LOGFNM="$DATE.md"
else
    LOGFNM="$TOPIC"_"$DATE.md"
fi

echo "editing $LOGFNM"

eval "$EDITOR $LBDIR"/"$LOGFNM"
