#! /bin/bash
set -e

DATE=`date +%Y-%m-%d`
TOPIC=""

args=`getopt t: "$*"`
set -- $args

for i ; do
    case "$i" in
        -t) TOPIC=$2 ; shift ; shift ;;
        --) shift ; break ;;
    esac
done

if [ -z ${LBEDITOR+x} ]; then
    LBEDITOR="vim"
fi

if [ -z ${LBDIR+x} ]; then
    LBDIR="$HOME/notes/"
fi

if [ ! -e $LBDIR ]; then
    mkdir -p $LBDIR
fi

if [ "$TOPIC" == "" ]; then
    LOGNAME="$DATE"
else
    LOGNAME="$TOPIC"_"$DATE"
fi

LOGFNM="$LBDIR"/"$LOGNAME".md

if [ ! -e $LOGFNM ] ; then
    echo "# $TOPIC $DATE" > $LOGFNM
fi

echo "editing $LOGNAME.md"

eval "$LBEDITOR $LOGFNM"
