#! /bin/bash

DATE=`date +%Y-%m-%d`
TOPIC=""

args=`getopt t: "$*"`
if [ $? != 0 ]; then
    echo "Usage: lb [-t TOPIC] [-d DIRNAME]"
    exit 1
fi

set -- $args

for i in $@; do
    case "$i" in
        -t) TOPIC=$2 ; shift ; shift ;;
        -d) LBDIR=$2 ; shift ; shift ;;
        --) shift ; break ;;
    esac
done

if [ -z ${LBEDITOR+nothing} ]; then
    LBEDITOR="vim"
fi

if [ -z "${LBDIR+nothing}" ]; then
    LBDIR="$HOME/notes"
fi

if [ ! -d "$LBDIR" ]; then
    mkdir -p "$LBDIR" || exit 1
fi

if [ "$TOPIC" == "" ]; then
    LOGNAME="$DATE"
else
    LOGNAME="$TOPIC"_"$DATE"
fi

LOGFNM="$LBDIR"/"$LOGNAME".md

if [ ! -e "$LOGFNM" ] ; then
    echo "# $TOPIC $DATE" | sed 's/\s\+/ /g' | tr _ - > "$LOGFNM"
fi

echo "editing $LOGNAME.md"

eval $LBEDITOR "\"$LOGFNM\""
